### ISSUE TITLE
[Feature Request] - Resource Group Support In config_targets/claim_target.py example

### ISSUE THREAD

**Issue by briamorr** [CiscoDevNet/intersight-python-utils#16]
[Feature Request] - Resource Group Support In config_targets/claim_target.py example

Currently in the example everything is claimed into the default organization which some users may not have permission to in a multi-tenant environment.  

Even in a single tenant environment, allowing to specify the resource group during device claim would help save a step post-claim in needing to move the device to the correct resource groups.

**Comment by dsoper2** [comment]
claim_target now supports resource groups and examples are updated to show usage.

**Comment by dsoper2** [comment]
claim_target now supports resource groups and examples are updated to show usage.
