### ISSUE TITLE
get_sha256_digest fails on data type

### ISSUE THREAD

**Issue by myfernandez** [CiscoDevNet/intersight-python-utils#21]
Hey guys, 
I'm playing with your lambda example for Intersight Webhooks and I'm getting the error below:

In this call:
[body_digest = get_sha256_digest(event['body'])](https://github.com/CiscoDevNet/intersight-python-utils/blob/2fd7d9ec4cf133e466ef237553f05d28298f8e8e/aws_lambda_webhook/intersight_alarms.py#L119)

event['body'] is of type dict, which makes 

[digest.update(data.encode())](https://github.com/CiscoDevNet/intersight-python-utils/blob/2fd7d9ec4cf133e466ef237553f05d28298f8e8e/aws_lambda_webhook/intersight_alarms.py#L56)

to fail as dictionaries do not have an encode method. 

`[ERROR] AttributeError: 'dict' object has no attribute 'encode'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 148, in lambda_handler
    verify_auth_header(event)
  File "/var/task/lambda_function.py", line 120, in verify_auth_header
    body_digest = get_sha256_digest(event['body'])
  File "/var/task/lambda_function.py", line 57, in get_sha256_digest
    digest.update(data.encode())
`

**Comment by dsoper2** [comment]
There's a print of the event dict in the current code - can you provide what you're seeing?  The event['body'] is a string in my environments:
>> event: {'resource': '/IntersightTMEAlarms', ..., 'body': '{"ObjectType":"mo.WebhookResult","ClassId":"mo.WebhookResult","AccountMoid":"62cc6a7b7564612d339dbfc5","DomainGroupMoid":"62cc6a7b7564612d339dbfc6","EventObjectType":"cond.Alarm"...

**Comment by myfernandez** [comment]
Yeah, it is different...my event['body'] is a dict:
```
event: {'method': 'POST', 'body': {'ObjectType': 'mo.WebhookResult',
```
So I suspect the difference is on the API GW side; how are you passing the headers?

I'm using this one:
```
{
    "method": "$context.httpMethod",
    "body" : $input.json('$'),
    "headers": {
        #foreach($param in $input.params().header.keySet())
        "$param": "$util.escapeJavaScript($input.params().header.get($param))"
        #if($foreach.hasNext),#end
        #end
    }
}
```

**Comment by dsoper2** [comment]
No header processing in my AWS API Gateway - the $input.json() call above will return a JS Object (https://developer.mozilla.org/en-US/docs/Web/API/Response/json) but the current code is expecting a string that's 
converted to JSON after the signature is calculated

**Comment by myfernandez** [comment]
Got it, changed my API GW, it works for me now. Thanks
